Escape % signs in migration 58 to fix IndexError: tuple index out of range
Full log

2024-09-04 15:46:24,149 - root - 355 - WARNING - main- ***** STARTING SERVER *****
2024-09-04 15:46:24,149 - root - 356 - WARNING - main- Server /usr/local/lib/python3.8/site-packages/synapse/app/homeserver.py version 1.113.0
2024-09-04 15:46:24,149 - root - 361 - WARNING - main- Copyright (c) 2023 New Vector, Inc
2024-09-04 15:46:24,149 - root - 362 - WARNING - main- Licensed under the AGPL 3.0 license. Website: https://github.com/element-hq/synapse
2024-09-04 15:46:24,149 - root - 365 - INFO - main- Server hostname: synapse0
2024-09-04 15:46:24,149 - root - 366 - INFO - main- Instance name: master
2024-09-04 15:46:24,149 - root - 367 - INFO - main- Twisted reactor: EPollReactor
2024-09-04 15:46:24,149 - synapse.app.homeserver - 370 - INFO - main- Setting up server
2024-09-04 15:46:24,149 - synapse.server - 353 - INFO - main- Setting up.
2024-09-04 15:46:24,153 - synapse.storage.SQL - 466 - DEBUG - main- [SQL] {startup} SET bytea_output TO escape
2024-09-04 15:46:24,153 - synapse.storage.SQL - 471 - DEBUG - main- [SQL values] {startup} ()
2024-09-04 15:46:24,153 - synapse.storage.SQL - 492 - DEBUG - main- [SQL time] {startup} 0.000351 sec
2024-09-04 15:46:24,153 - synapse.storage.SQL - 466 - DEBUG - main- [SQL] {startup} SET statement_timeout TO ?
2024-09-04 15:46:24,153 - synapse.storage.SQL - 471 - DEBUG - main- [SQL values] {startup} (3600000,)
2024-09-04 15:46:24,154 - synapse.storage.SQL - 492 - DEBUG - main- [SQL time] {startup} 0.000160 sec
2024-09-04 15:46:24,154 - synapse.storage.databases - 73 - INFO - main- [database config 'master']: Checking database server
2024-09-04 15:46:24,154 - synapse.storage.SQL - 466 - DEBUG - main- [SQL] {startup} SHOW SERVER_ENCODING
2024-09-04 15:46:24,154 - synapse.storage.SQL - 471 - DEBUG - main- [SQL values] {startup} ()
2024-09-04 15:46:24,154 - synapse.storage.SQL - 492 - DEBUG - main- [SQL time] {startup} 0.000325 sec
2024-09-04 15:46:24,154 - synapse.storage.SQL - 466 - DEBUG - main- [SQL] {startup} SELECT datcollate, datctype FROM pg_database WHERE datname = current_database()
2024-09-04 15:46:24,154 - synapse.storage.SQL - 471 - DEBUG - main- [SQL values] {startup} ()
2024-09-04 15:46:24,155 - synapse.storage.SQL - 492 - DEBUG - main- [SQL time] {startup} 0.000377 sec
2024-09-04 15:46:24,155 - synapse.storage.databases - 76 - INFO - main- [database config 'master']: Preparing for databases ['main', 'state']
2024-09-04 15:46:24,155 - synapse.storage.prepare_database - 135 - INFO - main- ['main', 'state']: Checking existing schema version
2024-09-04 15:46:24,155 - synapse.storage.SQL - 466 - DEBUG - main- [SQL] {prepare_database} COMMIT; BEGIN TRANSACTION; -- -- This file is licensed under the Affero General Public License (AGPL) version 3. -- -- Copyright (C) 2023 New Vector, Ltd -- -- This program is free software: you can redistribute it and/or modify -- it under the terms of the GNU Affero General Public License as -- published by the Free Software Foundation, either version 3 of the -- License, or (at your option) any later version. -- -- See the GNU Affero General Public License for more details: -- <https://www.gnu.org/licenses/agpl-3.0.html>. -- -- Originally licensed under the Apache License, Version 2.0: -- <http://www.apache.org/licenses/LICENSE-2.0>. -- -- [This file includes modifications made by New Vector Limited] -- -- /* Copyright 2015, 2016 OpenMarket Ltd * * Licensed under the Apache License, Version 2.0 (the "License"); * you may not use this file except in compliance with the License. * You may obtain a copy of the License at * *    http://www.apache.org/licenses/LICENSE-2.0 * * Unless required by applicable law or agreed to in writing, software * distributed under the License is distributed on an "AS IS" BASIS, * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. * See the License for the specific language governing permissions and * limitations under the License. */ CREATE TABLE IF NOT EXISTS schema_version( Lock CHAR(1) NOT NULL DEFAULT 'X' UNIQUE,  -- Makes sure this table only has one row. version INTEGER NOT NULL, upgraded BOOL NOT NULL,  -- Whether we reached this version from an upgrade or an initial schema. CHECK (Lock='X') ); CREATE TABLE IF NOT EXISTS schema_compat_version( Lock CHAR(1) NOT NULL DEFAULT 'X' UNIQUE,  -- Makes sure this table only has one row. -- The SCHEMA_VERSION of the oldest synapse this database can be used with compat_version INTEGER NOT NULL, CHECK (Lock='X') ); CREATE TABLE IF NOT EXISTS applied_schema_deltas( version INTEGER NOT NULL, file TEXT NOT NULL, UNIQUE(version, file) ); -- a list of schema files we have loaded on behalf of dynamic modules CREATE TABLE IF NOT EXISTS applied_module_schemas( module_name TEXT NOT NULL, file TEXT NOT NULL, UNIQUE(module_name, file) );
2024-09-04 15:46:24,155 - synapse.storage.SQL - 471 - DEBUG - main- [SQL values] {prepare_database} ()
2024-09-04 15:46:24,155 - synapse.storage.SQL - 492 - DEBUG - main- [SQL time] {prepare_database} 0.000139 sec
2024-09-04 15:46:24,155 - synapse.storage.SQL - 466 - DEBUG - main- [SQL] {prepare_database} SELECT version, upgraded FROM schema_version
2024-09-04 15:46:24,155 - synapse.storage.SQL - 471 - DEBUG - main- [SQL values] {prepare_database} ()
2024-09-04 15:46:24,155 - synapse.storage.SQL - 492 - DEBUG - main- [SQL time] {prepare_database} 0.000117 sec
2024-09-04 15:46:24,155 - synapse.storage.SQL - 466 - DEBUG - main- [SQL] {prepare_database} SELECT compat_version FROM schema_compat_version
2024-09-04 15:46:24,155 - synapse.storage.SQL - 471 - DEBUG - main- [SQL values] {prepare_database} ()
2024-09-04 15:46:24,155 - synapse.storage.SQL - 492 - DEBUG - main- [SQL time] {prepare_database} 0.000070 sec
2024-09-04 15:46:24,155 - synapse.storage.SQL - 466 - DEBUG - main- [SQL] {prepare_database} SELECT file FROM applied_schema_deltas WHERE version >= ?
2024-09-04 15:46:24,155 - synapse.storage.SQL - 471 - DEBUG - main- [SQL values] {prepare_database} (58,)
2024-09-04 15:46:24,155 - synapse.storage.SQL - 492 - DEBUG - main- [SQL time] {prepare_database} 0.000082 sec
2024-09-04 15:46:24,155 - synapse.storage.prepare_database - 139 - INFO - main- ['main', 'state']: Existing schema is 58 (+8 deltas)
2024-09-04 15:46:24,156 - synapse.storage.databases.main - 391 - INFO - main- Checking database for consistency with configuration...
2024-09-04 15:46:24,156 - synapse.storage.SQL - 466 - DEBUG - main- [SQL] {prepare_database} SELECT name FROM users LIMIT 1
2024-09-04 15:46:24,156 - synapse.storage.SQL - 471 - DEBUG - main- [SQL values] {prepare_database} ()
2024-09-04 15:46:24,156 - synapse.storage.SQL - 492 - DEBUG - main- [SQL time] {prepare_database} 0.000125 sec
2024-09-04 15:46:24,156 - synapse.storage.prepare_database - 422 - DEBUG - main- applied_delta_files: ('58/00background_update_ordering.sql', '58/02remove_dup_outbound_pokes.sql', '58/03persist_ui_auth.sql', '58/05cache_instance.sql.postgres', '58/06dlols_unique_idx.py', '58/07add_method_to_thumbnail_constraint.sql.postgres', '58/07persist_ui_auth_ips.sql', '58/08_media_safe_from_quarantine.sql.postgres')
2024-09-04 15:46:24,156 - synapse.storage.prepare_database - 433 - INFO - main- Applying schema deltas for v58
2024-09-04 15:46:24,156 - synapse.storage.SQL - 466 - DEBUG - main- [SQL] {prepare_database} DELETE FROM schema_version
2024-09-04 15:46:24,156 - synapse.storage.SQL - 471 - DEBUG - main- [SQL values] {prepare_database} ()
2024-09-04 15:46:24,156 - synapse.storage.SQL - 492 - DEBUG - main- [SQL time] {prepare_database} 0.000049 sec
2024-09-04 15:46:24,156 - synapse.storage.SQL - 466 - DEBUG - main- [SQL] {prepare_database} INSERT INTO schema_version (version, upgraded) VALUES (?,?)
2024-09-04 15:46:24,156 - synapse.storage.SQL - 471 - DEBUG - main- [SQL values] {prepare_database} (58, True)
2024-09-04 15:46:24,156 - synapse.storage.SQL - 492 - DEBUG - main- [SQL time] {prepare_database} 0.000052 sec
2024-09-04 15:46:24,156 - synapse.storage.prepare_database - 458 - DEBUG - main- Looking for schema deltas in /usr/local/lib/python3.8/site-packages/synapse/storage/schema/common/delta/58
2024-09-04 15:46:24,156 - synapse.storage.prepare_database - 458 - DEBUG - main- Looking for schema deltas in /usr/local/lib/python3.8/site-packages/synapse/storage/schema/main/delta/58
2024-09-04 15:46:24,156 - synapse.storage.prepare_database - 458 - DEBUG - main- Looking for schema deltas in /usr/local/lib/python3.8/site-packages/synapse/storage/schema/state/delta/58
2024-09-04 15:46:24,157 - synapse.storage.prepare_database - 497 - DEBUG - main- Found file: 58/00background_update_ordering.sql (/usr/local/lib/python3.8/site-packages/synapse/storage/schema/common/delta/58/00background_update_ordering.sql)
2024-09-04 15:46:24,157 - synapse.storage.prepare_database - 497 - DEBUG - main- Found file: 58/02remove_dup_outbound_pokes.sql (/usr/local/lib/python3.8/site-packages/synapse/storage/schema/main/delta/58/02remove_dup_outbound_pokes.sql)
2024-09-04 15:46:24,157 - synapse.storage.prepare_database - 497 - DEBUG - main- Found file: 58/03persist_ui_auth.sql (/usr/local/lib/python3.8/site-packages/synapse/storage/schema/main/delta/58/03persist_ui_auth.sql)
2024-09-04 15:46:24,157 - synapse.storage.prepare_database - 497 - DEBUG - main- Found file: 58/05cache_instance.sql.postgres (/usr/local/lib/python3.8/site-packages/synapse/storage/schema/main/delta/58/05cache_instance.sql.postgres)
2024-09-04 15:46:24,157 - synapse.storage.prepare_database - 497 - DEBUG - main- Found file: 58/06dlols_unique_idx.py (/usr/local/lib/python3.8/site-packages/synapse/storage/schema/main/delta/58/06dlols_unique_idx.py)
2024-09-04 15:46:24,157 - synapse.storage.prepare_database - 497 - DEBUG - main- Found file: 58/07add_method_to_thumbnail_constraint.sql.postgres (/usr/local/lib/python3.8/site-packages/synapse/storage/schema/main/delta/58/07add_method_to_thumbnail_constraint.sql.postgres)
2024-09-04 15:46:24,157 - synapse.storage.prepare_database - 497 - DEBUG - main- Found file: 58/07add_method_to_thumbnail_constraint.sql.sqlite (/usr/local/lib/python3.8/site-packages/synapse/storage/schema/main/delta/58/07add_method_to_thumbnail_constraint.sql.sqlite)
2024-09-04 15:46:24,157 - synapse.storage.prepare_database - 497 - DEBUG - main- Found file: 58/07persist_ui_auth_ips.sql (/usr/local/lib/python3.8/site-packages/synapse/storage/schema/main/delta/58/07persist_ui_auth_ips.sql)
2024-09-04 15:46:24,157 - synapse.storage.prepare_database - 497 - DEBUG - main- Found file: 58/08_media_safe_from_quarantine.sql.postgres (/usr/local/lib/python3.8/site-packages/synapse/storage/schema/main/delta/58/08_media_safe_from_quarantine.sql.postgres)
2024-09-04 15:46:24,157 - synapse.storage.prepare_database - 497 - DEBUG - main- Found file: 58/08_media_safe_from_quarantine.sql.sqlite (/usr/local/lib/python3.8/site-packages/synapse/storage/schema/main/delta/58/08_media_safe_from_quarantine.sql.sqlite)
2024-09-04 15:46:24,157 - synapse.storage.prepare_database - 497 - DEBUG - main- Found file: 58/09shadow_ban.sql (/usr/local/lib/python3.8/site-packages/synapse/storage/schema/main/delta/58/09shadow_ban.sql)
2024-09-04 15:46:24,157 - synapse.storage.prepare_database - 541 - INFO - main- Applying schema 58/09shadow_ban.sql
2024-09-04 15:46:24,157 - synapse.storage.SQL - 466 - DEBUG - main- [SQL] {prepare_database} COMMIT; BEGIN TRANSACTION; -- -- This file is licensed under the Affero General Public License (AGPL) version 3. -- -- Copyright (C) 2023 New Vector, Ltd -- -- This program is free software: you can redistribute it and/or modify -- it under the terms of the GNU Affero General Public License as -- published by the Free Software Foundation, either version 3 of the -- License, or (at your option) any later version. -- -- See the GNU Affero General Public License for more details: -- <https://www.gnu.org/licenses/agpl-3.0.html>. -- -- Originally licensed under the Apache License, Version 2.0: -- <http://www.apache.org/licenses/LICENSE-2.0>. -- -- [This file includes modifications made by New Vector Limited] -- -- /* Copyright 2020 The Matrix.org Foundation C.I.C * * Licensed under the Apache License, Version 2.0 (the "License"); * you may not use this file except in compliance with the License. * You may obtain a copy of the License at * *    http://www.apache.org/licenses/LICENSE-2.0 * * Unless required by applicable law or agreed to in writing, software * distributed under the License is distributed on an "AS IS" BASIS, * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. * See the License for the specific language governing permissions and * limitations under the License. */ -- A shadow-banned user may be told that their requests succeeded when they were -- actually ignored. ALTER TABLE users ADD COLUMN shadow_banned BOOLEAN;
2024-09-04 15:46:24,157 - synapse.storage.SQL - 471 - DEBUG - main- [SQL values] {prepare_database} ()
2024-09-04 15:46:24,168 - synapse.storage.SQL - 492 - DEBUG - main- [SQL time] {prepare_database} 0.010920 sec
2024-09-04 15:46:24,168 - synapse.storage.SQL - 466 - DEBUG - main- [SQL] {prepare_database} INSERT INTO applied_schema_deltas (version, file) VALUES (?,?)
2024-09-04 15:46:24,168 - synapse.storage.SQL - 471 - DEBUG - main- [SQL values] {prepare_database} (58, '58/09shadow_ban.sql')
2024-09-04 15:46:24,168 - synapse.storage.SQL - 492 - DEBUG - main- [SQL time] {prepare_database} 0.000081 sec
2024-09-04 15:46:24,168 - synapse.storage.prepare_database - 497 - DEBUG - main- Found file: 58/10_pushrules_enabled_delete_obsolete.sql (/usr/local/lib/python3.8/site-packages/synapse/storage/schema/main/delta/58/10_pushrules_enabled_delete_obsolete.sql)
2024-09-04 15:46:24,168 - synapse.storage.prepare_database - 541 - INFO - main- Applying schema 58/10_pushrules_enabled_delete_obsolete.sql
2024-09-04 15:46:24,168 - synapse.storage.SQL - 466 - DEBUG - main- [SQL] {prepare_database} COMMIT; BEGIN TRANSACTION; -- -- This file is licensed under the Affero General Public License (AGPL) version 3. -- -- Copyright (C) 2023 New Vector, Ltd -- -- This program is free software: you can redistribute it and/or modify -- it under the terms of the GNU Affero General Public License as -- published by the Free Software Foundation, either version 3 of the -- License, or (at your option) any later version. -- -- See the GNU Affero General Public License for more details: -- <https://www.gnu.org/licenses/agpl-3.0.html>. -- -- Originally licensed under the Apache License, Version 2.0: -- <http://www.apache.org/licenses/LICENSE-2.0>. -- -- [This file includes modifications made by New Vector Limited] -- -- /* Copyright 2020 The Matrix.org Foundation C.I.C. * * Licensed under the Apache License, Version 2.0 (the "License"); * you may not use this file except in compliance with the License. * You may obtain a copy of the License at * *    http://www.apache.org/licenses/LICENSE-2.0 * * Unless required by applicable law or agreed to in writing, software * distributed under the License is distributed on an "AS IS" BASIS, * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. * See the License for the specific language governing permissions and * limitations under the License. */ /** Delete stuck 'enabled' bits that correspond to deleted or non-existent push rules. We ignore rules that are server-default rules because they are not defined in the `push_rules` table. **/ DELETE FROM push_rules_enable WHERE rule_id NOT LIKE 'global/%/.m.rule.%' AND NOT EXISTS ( SELECT 1 FROM push_rules WHERE push_rules.user_name = push_rules_enable.user_name AND push_rules.rule_id = push_rules_enable.rule_id );
2024-09-04 15:46:24,168 - synapse.storage.SQL - 471 - DEBUG - main- [SQL values] {prepare_database} ()
2024-09-04 15:46:24,168 - synapse.storage.SQL - 488 - DEBUG - main- [SQL FAIL] {prepare_database} tuple index out of range, <built-in method execute of psycopg2.extensions.cursor object at 0x7fc0d8e1eb80>
2024-09-04 15:46:24,168 - synapse.storage.SQL - 492 - DEBUG - main- [SQL time] {prepare_database} 0.000016 sec
2024-09-04 15:46:24,168 - synapse.app._base - 220 - ERROR - main- Exception during startup
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/synapse/app/homeserver.py", line 373, in setup
    hs.setup()
  File "/usr/local/lib/python3.8/site-packages/synapse/server.py", line 355, in setup
    self.datastores = Databases(self.DATASTORE_CLASS, self)
  File "/usr/local/lib/python3.8/site-packages/synapse/storage/databases/__init__.py", line 81, in __init__
    prepare_database(
  File "/usr/local/lib/python3.8/site-packages/synapse/storage/prepare_database.py", line 156, in prepare_database
    _upgrade_existing_database(
  File "/usr/local/lib/python3.8/site-packages/synapse/storage/prepare_database.py", line 542, in _upgrade_existing_database
    database_engine.execute_script_file(cur, absolute_path)
  File "/usr/local/lib/python3.8/site-packages/synapse/storage/engines/_base.py", line 155, in execute_script_file
    cls.executescript(cursor, f.read())
  File "/usr/local/lib/python3.8/site-packages/synapse/storage/engines/postgres.py", line 259, in executescript
    cursor.execute(f"COMMIT; BEGIN TRANSACTION; {script}")
  File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 424, in execute
    self._do_execute(self.txn.execute, sql, parameters)
  File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 486, in _do_execute
    return func(sql, *args, **kwargs)
IndexError: tuple index out of range