Fix missing semmicolons in migration 54
Fix te following error:

LINE 49: CREATE UNIQUE INDEX account_validity_renewal_string_idx ON a...

Full corresponding log:

2024-09-04 12:21:16,378 - root - 355 - WARNING - main- ***** STARTING SERVER *****
2024-09-04 12:21:16,378 - root - 356 - WARNING - main- Server /usr/local/lib/python3.8/site-packages/synapse/app/homeserver.py version 1.113.0
2024-09-04 12:21:16,378 - root - 361 - WARNING - main- Copyright (c) 2023 New Vector, Inc
2024-09-04 12:21:16,378 - root - 362 - WARNING - main- Licensed under the AGPL 3.0 license. Website: https://github.com/element-hq/synapse
2024-09-04 12:21:16,378 - root - 365 - INFO - main- Server hostname: synapse0
2024-09-04 12:21:16,378 - root - 366 - INFO - main- Instance name: master
2024-09-04 12:21:16,378 - root - 367 - INFO - main- Twisted reactor: EPollReactor
2024-09-04 12:21:16,378 - synapse.app.homeserver - 370 - INFO - main- Setting up server
2024-09-04 12:21:16,378 - synapse.server - 353 - INFO - main- Setting up.
2024-09-04 12:21:16,383 - synapse.storage.databases - 73 - INFO - main- [database config 'master']: Checking database server
2024-09-04 12:21:16,383 - synapse.storage.databases - 76 - INFO - main- [database config 'master']: Preparing for databases ['main', 'state']
2024-09-04 12:21:16,383 - synapse.storage.prepare_database - 135 - INFO - main- ['main', 'state']: Checking existing schema version
2024-09-04 12:21:16,384 - synapse.storage.prepare_database - 139 - INFO - main- ['main', 'state']: Existing schema is 53 (+7 deltas)
2024-09-04 12:21:16,384 - synapse.storage.databases.main - 391 - INFO - main- Checking database for consistency with configuration...
2024-09-04 12:21:16,384 - synapse.storage.prepare_database - 433 - INFO - main- Applying schema deltas for v53
2024-09-04 12:21:16,384 - synapse.storage.prepare_database - 541 - INFO - main- Applying schema 53/users_in_public_rooms.sql
2024-09-04 12:21:16,402 - synapse.storage.prepare_database - 433 - INFO - main- Applying schema deltas for v54
2024-09-04 12:21:16,402 - synapse.storage.prepare_database - 541 - INFO - main- Applying schema 54/account_validity_with_renewal.sql
2024-09-04 12:21:16,403 - synapse.app._base - 220 - ERROR - main- Exception during startup
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/synapse/app/homeserver.py", line 373, in setup
    hs.setup()
  File "/usr/local/lib/python3.8/site-packages/synapse/server.py", line 355, in setup
    self.datastores = Databases(self.DATASTORE_CLASS, self)
  File "/usr/local/lib/python3.8/site-packages/synapse/storage/databases/__init__.py", line 81, in __init__
    prepare_database(
  File "/usr/local/lib/python3.8/site-packages/synapse/storage/prepare_database.py", line 156, in prepare_database
    _upgrade_existing_database(
  File "/usr/local/lib/python3.8/site-packages/synapse/storage/prepare_database.py", line 542, in _upgrade_existing_database
    database_engine.execute_script_file(cur, absolute_path)
  File "/usr/local/lib/python3.8/site-packages/synapse/storage/engines/_base.py", line 155, in execute_script_file
    cls.executescript(cursor, f.read())
  File "/usr/local/lib/python3.8/site-packages/synapse/storage/engines/postgres.py", line 259, in executescript
    cursor.execute(f"COMMIT; BEGIN TRANSACTION; {script}")
  File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 424, in execute
    self._do_execute(self.txn.execute, sql, parameters)
  File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 486, in _do_execute
    return func(sql, *args, **kwargs)
psycopg2.errors.SyntaxError: syntax error at or near "CREATE"
LINE 49: CREATE UNIQUE INDEX account_validity_renewal_string_idx ON a...